### ISSUE TITLE
Don‘t use strict versions of dependencies

### ISSUE THREAD

**Issue by yuchi** [evenchange4/react-intl-cra#29]
Looks like you have all your `dependencies` set as strict versions.

This makes it very difficult for package managers to deduplicate them with those installed for other reasons.

I suggest you to use the recommended caret-range.

**Comment by evenchange4** [comment]
@yuchi Thank your recommendation!!
I should setup __renovate__ with `config:js-lib` for js library. 👍

**Comment by evenchange4** [comment]
Thanks! Released `v0.3.3`
